### ISSUE TITLE
Add Ability to Specify Service Labels

### ISSUE THREAD

**Issue by prpercival** [memgraph/helm-charts#118]
Would it be possible to add `service.labels` as a parameter in the helm chart in [values.yaml](https://github.com/memgraph/helm-charts/blob/88c1a05bc437753b78e67cdb3c0b55ad1c5ae616/charts/memgraph/values.yaml#L28)? Currently our Cilium deployment relies on these to allocate IP for access outside of the cluster. It doesn't seem like there is an easy way currently to accomplish this with the helm chart. I appreciate any help you can offer!

Here's am example of what I'm imaging based off of the [bitnami redis cluster helm chart](https://github.com/bitnami/charts/tree/main/bitnami/redis-cluster).

```
values:
    service:
      type: LoadBalancer
      loadBalancerIP: PLACEHOLDER
      externalAccess: true
      labels:
        service: PLACEHOLDER # matched by CiliumLoadBalancerIPPool
        cilium: l2-announce # matched by CiliumL2AnnouncementPolicy
```
