### ISSUE TITLE
[Bug]: memgraph containers not running with least privilege security context

### ISSUE THREAD

**Issue by tmyhu** [memgraph/helm-charts#36]
### What happened?

I'd like to suggest a couple of improvements to the securityContext in the StatefulSet of standalone memgraph helm chart. I've successfully tested these in our installation with the chart version 0.1.3:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: residency
spec:
  template:
    spec:
      initContainers:
        - name: init-volume-mounts
          securityContext:
            # Runs only chown on the mounted PVC so no need to write to root fs
            readOnlyRootFilesystem: true
            # `ALL` instead of `all` - case matters, see https://github.com/kubernetes/pod-security-admission/issues/11
            capabilities:
              drop:
                - ALL
      containers:
        - name: memgraph
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
```

In addition it may be helpful to add the securityContext settings to the default values to make it more transparent and allow users to change them in case of edge cases that may not work with the defaults.

### Chart type

Standalone

### Chart version

0.1.3

### Environment

Kubernetes 1.27

**Comment by antejavor** [comment]
Hi @tmyhu, thanks for bringing this to our attention and opening the issue, I will take a look.

**Comment by ricker-flow** [comment]
The security context set to `privileged: true` prevents the helm chart from running on Google Kubernetes Engine (GKE)

**Comment by antejavor** [comment]
HI @ricker-flow thanks for communicating this, this is currently `true` for running the init-containers before Memgraph is being run and setting the ownership of volumes, I wasn't aware GKE blocks this. 

Have you been able to create a workaround around this? I guess we should look at how to fix that permission issue.

**Comment by ricker-flow** [comment]
There is no need to run `containerInit`. Instead set `securityContext`.  

This is the entire stateful set spec that works on GKE. No privileges needed. File ownership is automatic. 

```
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: memgraph
      app.kubernetes.io/name: memgraph
  serviceName: memgraph
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: memgraph
        app.kubernetes.io/name: memgraph
        app.kubernetes.io/version: 2.20.0
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - args:
            - --also-log-to-stderr=true
          image: memgraph/memgraph:2.20.0
          imagePullPolicy: IfNotPresent
          name: memgraph
          ports:
            - containerPort: 7687
              name: bolt
            - containerPort: 7444
              name: websocket
            - containerPort: 9091
              name: http
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /var/lib/memgraph
              name: memgraph-lib-storage
            - mountPath: /var/log/memgraph
              name: memgraph-lib-storage
      terminationGracePeriodSeconds: 1800
      volumes:
        - name: memgraph-lib-storage
          persistentVolumeClaim:
            claimName: memgraph-lib-storage
        - name: memgraph-log-storage
          persistentVolumeClaim:
            claimName: memgraph-log-storage
```
