### ISSUE TITLE
[Bug]: Volume mount name for log storage is incorrect

### ISSUE THREAD

**Issue by dintorf** [memgraph/helm-charts#60]
### Contact Details

No response

### What happened?

The volume mount name for the log storage claim is incorrect. It points to the lib storage claim.

https://github.com/memgraph/helm-charts/blob/main/charts/memgraph/templates/statefulset.yaml#L181-L184

```yaml
          {{- if .Values.persistentVolumeClaim.createLogStorage }}
            - name: {{ include "memgraph.fullname" . }}-lib-storage # here is the incorrect line
              mountPath: /var/log/memgraph
          {{- end }}
```

Should be changed to 

```yaml
          {{- if .Values.persistentVolumeClaim.createLogStorage }}
            - name: {{ include "memgraph.fullname" . }}-log-storage # should be log-storage here instead of lib-storage
              mountPath: /var/log/memgraph
          {{- end }}
```

### Chart type

Standalone

### Chart version

0.1.x

### Environment

My environment is not listed

### Relevant log output

No response
