### ISSUE TITLE
[Bug]: Contributions - Please provide a pre-commit or something to enforce formatting

### ISSUE THREAD

**Issue by jseiser** [memgraph/helm-charts#8]
### Contact Details

justinseiser@gmail.com

### What happened?

When contributing to this chart, it would be nice if you all provided some sort of pre-commit or something similar so all of our code was forced to be formatted the same way.  Same with generating a readme, or providing some sort of linter_values.yaml that has to be ran etc.

Im much more familiar with Gitlab, than github, but being able to enforce these things locally, will def. make passing your Github CI easier for us when we contribute.

Example pre-commit
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      - id: no-commit-to-branch

      # Common errors
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: CHANGELOG.md
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

      # Security
      - id: detect-private-key

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0
    hooks:
      - id: helm-docs
```

### Chart type

Standalone

### Chart version

0.1.0

### Environment

Local Machine
